### ISSUE TITLE
No `bunfig.toml` when creating with a non-default registry

### ISSUE THREAD

**Issue by nick-cjyx9** [akirarika/create-milkio#9]
![image](https://github.com/user-attachments/assets/571f0170-c37a-458e-8b65-9b03a897365a)

https://github.com/akirarika/create-milkio/blob/0c6f04e0c57ce36efdd555c8b379a9e23111f0be/index.mjs#L184

readFile uses 'r' flag by default, which will raise exception when the file do not exist, how about set it to `a` or check the existence before operate toml?

OS: windows 11

**Comment by akirarika** [comment]
Fixed!

This was a bug introduced a few days ago. When you don't select a mirror source, it won't add the bun.toml file
